language: rust
rust:
- nightly
- beta
- stable
os:
- osx
env:
- FEATURES="OSX_10_9"
- FEATURES=""
script:
- (cd security-framework-sys && cargo build --features "$FEATURES")
- (cd security-framework && env RUST_TEST_THREADS=1 cargo test --features "$FEATURES")
