language: rust
rust:
- nightly
- beta
- 1.4.0
os:
- osx
env:
- FEATURES="OSX_10_9"
- FEATURES=""
script:
- env RUST_TEST_THREADS=1 cargo test --manifest-path=security-framework/Cargo.toml --features "$FEATURES"
