[package]
name = "security-framework"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"

[dependencies]
security-framework-sys = { path = "../security-framework-sys" }
core-foundation = "0.2"
core-foundation-sys = "0.2"
libc = "0.2"

[dev-dependencies]
tempdir = "0.3"
rustc-serialize = "0.3"

[features]
OSX_10_8 = ["security-framework-sys/OSX_10_8"]
OSX_10_9 = ["OSX_10_8", "security-framework-sys/OSX_10_9"]
OSX_10_10 = ["OSX_10_9", "security-framework-sys/OSX_10_10"]
OSX_10_11 = ["OSX_10_10", "security-framework-sys/OSX_10_11"]
