[package]
name = "security-framework"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"

[dependencies]
security-framework-sys = { path = "../security-framework-sys" }
libc = "0.1"

[features]
OSX_10_8 = ["security-framework-sys/OSX_10_8"]
OSX_10_9 = ["OSX_10_8", "security-framework-sys/OSX_10_9"]
OSX_10_10 = ["OSX_10_9", "security-framework-sys/OSX_10_10"]
